version: '3'
services:
 nginx:
   image: nginx:1-alpine
   depends_on:
     - web
   volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./www/:/usr/share/nginx/html/
   ports:
     - "8084:80"
 web:
   build: .
   volumes:
    - ./sandbox.ini:/usr/local/etc/php/conf.d/sandbox.ini
    - ./flag_phpbyp4ss:/var/www/flag_phpbyp4ss
